name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  oj-verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1  # use checkout@v1 for oj-verify's timestamp

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Cache test cases
        uses: actions/cache@v2
        with:
          path: ./.verify-helper/cache
          key: ${{ runner.os }}-verify-helper-${{ hashFiles('**/*.test.cpp') }}
          restore-keys: |
            ${{ runner.os }}-verify-helper-
      - name: Run tests & Generate documents
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: oj-verify all --jobs 2

      - name: Upload timestamp
        uses: actions/upload-artifact@v3
        with:
          name: timestamp
          path: .verify-helper/timestamps.remote.json

      - name: Upload documents
        uses: actions/upload-artifact@v3
        with:
          name: oj-documents
          path: .verify-helper/markdown

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Pull docker (paperist/texlive-ja)
        run: docker pull paperist/texlive-ja:latest

      - name: Download jlisting.sty
        run: |
          wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
          bunzip2 jlisting.sty.bz2
      - name: Make PDF
        run: |
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_1col.tex
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_2col.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: library-PDF
          path: main_*.pdf

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [oj-verify, build]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Download timestamp
        uses: actions/download-artifact@v3
        with:
          name: timestamp
          path: .verify-helper

      - name: Download documents
        uses: actions/download-artifact@v3
        with:
          name: oj-documents
          path: .verify-helper/markdown

      - name: Download PDF
        uses: actions/download-artifact@v3
        with:
          name: library-PDF



      - name: Commit PDF and timestamp
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update Library'
          default_author: github_actions
          add: '["*.pdf", .verify-helper/timestamps.remote.json]'