name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
#     - name: update
#       run: sudo apt-get update
    
    - uses: actions/checkout@v1 # use checkout@v1 for oj-verify's timestamp

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install boost
      run: sudo apt install -y libboost-dev

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Cache test cases
      uses: actions/cache@v3
      with:
        path: ./.verify-helper/cache
        key: ${{ runner.os }}-verify-helper-${{ hashFiles('**/*.test.cpp') }}
        restore-keys: |
          ${{ runner.os }}-verify-helper-
    
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: oj-verify all --jobs 2
